[Lily] 2w - main view (grid type)
codesquad-members-2023/fe-news pull request #14
Opened 2023-04-10 07:20 UTC by ahnlook

## 가장 고민했던 부분
**(4/10)** UI를 다루는 class와 로직을 처리하는 class를 분리하고 싶었다. 분리를 하다보니 data가 전달, 전달, 전달 반복되다보니 효율적인지에 대한 고민이 들었다.

2023-04-12 08:46 UTC, bread1022 reviewed
element 속성, 클래스를 직관적으로 생성해서 이해하기 좋았던 것같아요 ! 🙌🏻

2023-04-12 08:46 UTC, bread1022 commented on src/pages/mainSection/mainDirectionBtn.js
> +    }
클래스 내부 메서드를 활용한 버튼 조작 로직이 깔끔하고 좋아보이네요 !!! 다만, 여기서 If 문 depth가 있다보니 `if(!leftBtn && !rightBtn) return;`으로 depth를 줄여봐도 좋을 것 같아요 ෆ

2023-04-12 08:46 UTC, bread1022 commented on src/pages/mainSection/mainDirectionBtn.js
> +customElements.define('ns-direction-btn', MainDirectionBtn)
`define`메서드로 `customElements` 를 정의하면 전역에서 사용가능한건가요 ????

2023-04-12 08:46 UTC, bread1022 commented on src/pages/mainSection/mainHandler.js
> +    return data.sort(() => Math.random() - 0.5)
`0.5` 는 무엇을 의미하는 건가요 ?

2023-04-12 08:46 UTC, bread1022 commented on src/pages/mainSection/mainHandler.js
> +      const pressName = cell?.querySelector('.press img').alt
`?.` 옵셔널체이닝 메서드 활용을 항상 못 했었는데 querySelector 확인할 때 사용하기 정말 좋아보여요 !!!

2023-04-12 08:46 UTC, bread1022 commented on src/pages/mainSection/mainHandler.js
> +    const slicedData = this.#data.slice(startPress, endPress)
grid 배열을 받아서 페이지를 변경하는 게 아니라 그 안에 item을 slice 하는 건가요 ? 이 방법도 너무 좋네요 !

2023-04-12 09:55 UTC, ahnlook commented on src/pages/mainSection/mainDirectionBtn.js
> +customElements.define('ns-direction-btn', MainDirectionBtn)
네! js에서 create element 할 수도 있고 html에서 `<ns-direction-btn></ns-direction-btn>` 이렇게도 사용 가능해요!

2023-04-12 09:55 UTC, ahnlook commented on src/pages/mainSection/mainDirectionBtn.js
> +    }
나니 짱! 감사합니다!

2023-04-12 09:58 UTC, ahnlook commented on src/pages/mainSection/mainHandler.js
> +    return data.sort(() => Math.random() - 0.5)
Math.random() - 0.5는 0에서 1 사이의 임의의 부동 소수점 값을 반환하고, 이 값에 0.5를 뺀 결과는 -0.5에서 0.5 사이의 값을 갖습니다. 이 값이 음수이면 두 요소가 무작위로 섞인 다음 첫 번째 요소가 두 번째 요소보다 앞에 오도록 합니다. 이 값이 양수이면 두 요소가 무작위로 섞인 다음 첫 번째 요소가 두 번째 요소보다 뒤에 오도록 합니다.

라고 하네요 GPT가..

2023-04-12 10:00 UTC, ahnlook commented on src/pages/mainSection/mainHandler.js
> +    const slicedData = this.#data.slice(startPress, endPress)
나니가 말씀하신 item = data가 맞을까요? grid를 만드는 js 파일로 필요한 만큼의 data를 보내주는 방식으로 했습니다!

2023-04-13 01:47 UTC, crongro commented
> 언론사 별 구독 상태를 저장해야 하는데 현재는 따로 저장을 하지 않았나. 배열에만 넣어뒀다. local storage에 저장을 해야할지, server에 post를 해야할지 고민 중이다!

로그인 베이스 서비스이면 당연히 서버에 저장하겠네요. 우리는 로컬에 저장해도 될 듯.

2023-04-13 01:56 UTC, crongro requested changes
디자인패턴을 고민하시던데 보기 좋았어요. 완전한 구조는 없으니 현재 상황에서 개선점을 찾는과정이 중요한것 같습니다.

css 모듈로 나눈것 좋고요.
init.css 보다는 reset 이라는 표현을 더하긴합니다.
참고로. 생성자에 파라미터를 받지 않는 클래스는 싱글톤패턴으로 적용되는 것이라 객체리터럴 문법으로 표현하는것도 가능하긴합니다. 

headerUI는 알겠는데 이름만 봐서는 header.js 라고 하면 컨트롤러역할인지 컨테이너같은건지 잘 모르겠어요.

DOM 추가작업시 이제는 템플릿리터럴을 사용하세요.

then 표현보다 await 사용해보세요. 

fetch 할때 URL은 파라미터로 받으세요(함수나 클래스 생성자에서.)

파일에 UI , View 라고 여러개를 사용하는데 비슷한것 같아요. 혼용하지 않으면 좋겠어요.

/mainSection/MainGridCellUI 라고 하시는데 main이라는 파일이름이 중복이고요. gridcell 은 구조를 나타냄으로 그것보다는 그 영역의 의미를 이름으로 지어보세요.

수정하시고 다시 PR보내세요~

2023-04-13 04:34 UTC, ahnlook commented
> Changes requested

수정 완료했습니다 :)

2023-04-14 01:28 UTC, crongro approved these changes
확인했어요.
수고하셨어요.

2023-04-14 01:28 UTC, merged