[sarang_daddy] 2주차
codesquad-members-2023/fe-news pull request #15
Opened 2023-04-10 09:20 UTC by sarangdaddy

상태관리의 필요성과 개념을 먼저 공부하고 2주차 미션 구현을 진행해야겠다.

2023-04-12 06:13 UTC, realsnoopso commented on src/api/getData.js
> +};
.then 말고 await로 바꾸면 더 보기 좋을 것 같아요!

2023-04-12 06:16 UTC, realsnoopso commented on src/components/journalList/journalListView.js
> +  const journalURL = " http://localhost:3000/journal";
띄어쓰기가 있어요!

2023-04-12 06:26 UTC, realsnoopso commented on src/api/getData.js
> +      return journal.makeJournal();
api 폴더 안에 있는 파일인데 Journal 이라는 html 태그를 생성하는 클래스가 여기에서 선언되는게 어색한거 같아요.
api 파일이라고 하면 로직만 담고 있을 것 같거든요. view와 controller 영역을 분리해보면 좋을 것 같아요.

2023-04-12 06:27 UTC, realsnoopso commented on src/getData/journalData.js
> +    result.push(obj);
forEach 대신 map을 쓰면 .push 메소드를 사용하지 않고도 array 를 반환할 수 있을 것 같아요.

2023-04-12 06:29 UTC, realsnoopso commented on src/main.js
> +    createNewsStandHeadLine(),
마찬가지로 view에 관한 처리가 여기 오니까 어색하다고 느껴져요.
+ getData라는 폴더명이 api/components 들과 위계가 안맞는 것처럼 느껴져서 (getData만 동사이고 나머지는 명사임) 폴더명을 수정하는 것도 고려해보면 좋을 것 같아요

2023-04-12 06:32 UTC, realsnoopso commented on src/components/journalList/journalCarousel.js
> +  }
if (this.page === FIRST_PAGE) {
    ...
    return ...
}

if (this.page === LAST_PAGE) {
    ...
    return ...
}

... (나머지 코드)

로 else if 와 else 를 수정할 수 있을 것 같아요

2023-04-12 06:33 UTC, realsnoopso commented on src/components/journalList/journalCarousel.js
> +  this.leftBtn.style.display = "none";
이렇게 일일히 style을 조작하는 것보다는 class를 만들고 class 안에 해당 속성을 담은 후 클래스를 조작하는 것이 더 깔끔할 것 같아요. (추후 확장성 고려 차원)

2023-04-13 02:11 UTC, crongro requested changes
screen 아래 css 파일들이 보이는데 screen 이라는 이름은 잘 안쓸거 같긴해요.(중요한건 아님)

css파일에 공통으로 사용할만한 유용한 클래스가 부족해보이네요. 중복되는 것을 클래스로 만들어서 재사용해보세요.

async 함수를 활용해서 익혀보시고, try / catch 도 해보세요.

Dispatcher/journalDispatcher.js 는 데이터 요청에 책임이 있는것이지 dispatch 하는 책임은 아닌것 같아요. 따라서 디렉토리/파일이름에 dispatcher 가 붙어야 할까? 고민스럽네요. 

안쓰는 코드 주석은 모두 삭제하고 커밋하세요.

headerlineclass 처럼 구조를 이름에 넣지 마세요.

ES Class 메서드에서는 function 키워드를 생략할 수 있어요.

makeHeadline 보다는 getHeadLineHTML 이 나아보입니다.

Caroulse prototype 패턴은 잘 하셨는데 생성자에서 몇 개 파라미터를 받으면 더 좋을듯.

위 내용 수정해서 다시 커밋/푸시 해서 보내주세요.

2023-04-14 01:30 UTC, crongro approved these changes
수고하셨어요. 머지합니다~

2023-04-14 01:30 UTC, crongro commented on src/components/journalList/journalClass.js
> +  getJournalItem() {
다음엔 이정도 함수는 더 작은 함수 몇개로 나눠보세요.

2023-04-14 01:30 UTC, merged