[Poco] 뉴스스탠드 2주차 학습계획
codesquad-members-2023/fe-news pull request #16
Opened 2023-04-10 10:34 UTC by poco111

### 🎯 고민
옵저버 패턴과 flux 아키텍쳐에 대해서 확실하게 공부를 해야하고 미션을 구현해야겠다

설계를 할 때, 작은 기능들을 놓친 부분에서 반복해서 수정사항이 발생하고 있다

앞으로 구현할 부분에 대해서는 꼼꼼하게 설계를 하고 진행해야겠다.

---

### 🎯 학습 계획

📣 설계….설계…. 그리고 설계

store와 view의 이별

state(상태) -> rendering 방식의 흐름으로 프로그래밍

📣 옵저버 패턴

📣 flux 아키텍처

📣 css 선언 순서 지키기

📣 file 한개에 한개의 class(객체) 구현하기

📣 ES module 사용해서 중복 코드 줄이기

---

### 🎯 구현

⭐⭐⭐⭐⭐⭐ 옵저버 패턴, flux ⭐⭐⭐⭐⭐⭐

⭐ 기획서, 요구사항 꼼꼼하게 읽기

⭐ 옵저버 패턴, flux 아키텍쳐 학습 먼저하기

⭐ 추가적인 기능들을 생각해서 설계 추가 완료하기

⭐ 1주차 미완성 부분 - rolling 영역, grid 부터 완성하기

⭐ 주요 요구사항

### 최신 뉴스 롤링영역

- [x]  좌우 바는 각각 다른 최신 뉴스의 헤드라인 5개가 5초마다 자동 무한 롤링
    - [x]  좌우 영역의 시간차를 1초로 하여 동시에 롤링되지 않게 하기
- [ ]  각 영역에 마우스를 호버하면, 무한 롤링 일시정지 및 헤드라인에 밑줄 표시하기

### 언론사별 기사들을 확인하는 영역

- [ ]  [전체 언론사] 탭의 [그리드 보기] 기본상태로 하기
- [ ]  가로 930px, 세로 388px의 영역에 6*4 테이블 만들기
    - [ ]  언론사는 아무리 많아도 4페이지까지만 표시하기
- [ ]  각 테이블 셀에 언론사 브랜드 마크 중앙에 배치
- [ ]  언론사 브랜드 마크의 순서는 페이지 새로고침 될 때마다 랜덤으로 배치 시키기
- [ ]  그리드 좌우에 화살표를 배치해서 페이지를 넘길 수 있게 하기
    - [ ]  가장 첫 페이지와 끝 페이지에는 disabled 되는 화살표는 아예 표시하지 않기

### 전체 언론사
- [ ] 구독/해지 버튼을 클릭했을 때 발생하는 grid 변화

### 리스트 UI
- [ ] 리스트 화면구성(HTML, CSS)
- [ ] 탭 UX
- [ ] 페이지 이동
- [ ] 프로그래스바 애니메이션
- [ ] 구독 / 해지 버튼을 클릭했을 때 발생하는 리스트 변화

📣 어떤 식으로 구현했는지 구체적으로 기록하기

---

### 🎯 학습

- [ ]  옵저버 패턴
- [ ]  flux 아키텍쳐
- [ ]  webpack

2023-04-12 07:05 UTC, sjuhan123 commented on src/js/domMaker/headerMaker.js
> +      <a onClick="window.location.reload()">
이벤트를 이렇게 간단하게 등록하는 방법이 있었군요 ㅎㅎ 참고하겠습니다

2023-04-12 07:28 UTC, sjuhan123 commented on src/js/dataFetcher/dataFetcher.js
>      this.data;
this.data를 get하고 싶으면, 외부에서 getResult 메서드만 사용해서 접근해야 되는데 this.data가 public 상태다 보니 해당 메서드를 사용 안해도 외부에서 data에 접근 가능합니다. 이를 방지하는 방법이 몇 가지 있던데 어떤게 최선일까요..? 저도 고민 중인 부분입니다 ㅎㅎ..

2023-04-12 07:33 UTC, sjuhan123 commented on src/js/const/const.js
> +
상수들을 따로 모아 놓으니까 관리하기도 편할 것 같고 너무 좋네요! 저도 참고하겠습니다😀

2023-04-13 02:22 UTC, crongro requested changes
로직을 함수로 감싸는 것이 늘 좋은데, main 함수는 감싸지 않아도 될 정도로 보이긴 하네요.객체초기화만 하고 있어서요.

HEADERModel -> NSHeaderModel 로 대문자로만 쓰지 않으면 좋을 듯.

domMaker 는 DOM이라는 약자를 포함하고 있으니 오히려 DOMMaker 라고 하는것이 좋고요.

HEADModel 에 상태(state)가 무엇인지 고민해보세요. 변경되는 부분이 state 인데 그런부분이 어떤것인지? 그것이 상태의 대상이 됩니다. title, imgAlt 가 상태관리가 필요한 아이일까요? 그냥 정적인 데이터 같아서요.

dataFetcher.js 는 유틸리티 클래스일까요? 그런용도면 좋겠네요.

newsstandview.js. 는 왜 /view 디렉토리 안에 위치하지 않나요? view로 옮겨도 되고, 만약 headerxxxview.js 가 하위뷰라면 디렉토리를 만들어서 계층구조를 표현하고요.

Const, crawl 처럼 괜히 줄이지 말고 원래 단어를 다 쓰세요.

이건 그냥 고민해보세요. Header관련 파일이 dommaker/view 로 나눠져 있는데 이게 좋을지,이게 합치는것이 더 나을지? 장단점은 무엇인지 등등. 늘 고민스러운 내용이거든요.


수고하셨어요.
참고해서 수정하시고 다시 push!  해주세요.

2023-04-14 05:31 UTC, crongro approved these changes
수고하셨어요!
머지할게요.

2023-04-14 05:31 UTC, crongro commented on src/js/constant/dom.js
> +const REFERENCE = Object.freeze({
Object.freeze 로 얻어지는 장점이 무엇인지  알고 있죠? 좋습니다.

2023-04-14 05:31 UTC, crongro commented on src/js/view/NSHeaderView.js
> +  constructor({ NS_HEADER_INFO }, REFERENCE) {
근데, 
저거 대문자 파라미터들 상수죠? 상수객체? 아무튼 그런 상수는 생성자에 받는것보다 그냥import 받아서 객체에서 직접 참고해도 될것 같아요.  
변경되는 값은 생성자로 받는것도 의미있을것 같고요.

2023-04-14 05:31 UTC, crongro commented on src/js/view/NSHeadlineView.js
> +    await this._dataFetcher.fetchData(this._API_PATH.HEADLINE);
이건 아까 말했던거~

2023-04-14 05:31 UTC, merged