[den] 2주차/mid
codesquad-members-2023/fe-news pull request #18
Opened 2023-04-10 11:19 UTC by sjuhan123

## Week2 학습계획

### Week2: model-view 역할분리

**:one: 월요일 학습계획**

- [x] : 기능 구현
  - [x] : grid hover시 구독하기 버튼 나타나게 구현
  - [x] : 구독하기 버튼 클릭시 해지하기 버튼 구현
  - [x] : 구독하기 버튼 클릭시 '내가 구독한 언론사' 탭에 해당 언론사 추가 기능 구현
  - [x] : 해지하기 버튼 클릭시 '내가 구독한 언론사' 탭에서 해당 언론사 삭제 기능 구현
  - [x] : 구독하기 버튼 연속 클릭시 '내가 구독한 언론사' 탭에 해당 언론사 계속 추가 되지 않도록 차단 기능 구현
  - [x] : '내가 구독한 언론사'탭의 리스트가 24개 이하일 때 버튼 노출되지 않도록 구현
  - [x] : '내가 구독한 언론사'탭에서 다시 '전체 언론사' 탭으로 돌아 왔을 때 각 언론사별 구독 여부 데이터 유지되게끔 구현
- [ ]: 기능 구현 이후 코드 리팩토링 진행

**:two: 화요일 학습계획**

- [ ] : scss 개념 학습 및 설치
- [ ] : scss 프로젝트에 적용
  - [ ] : header 영역 적용
  - [ ] : trend 영역 적용
  - [ ] : main view 영역 적용

**:three: 수요일 학습계획**

- [ ] : store 개념 학습
- [ ] : store 개념 코드에 적용

**:four: 목요일 학습계획**

- [ ] : trend 롤링바 구현

**:five: 금요일 학습계획**

- [ ] : list뷰 구현

2023-04-12 07:08 UTC, poco111 commented on src/components/Header.js
> +    const formattedDate = date.toLocaleString("ko-KR", options);
toLocaleString 메서드 활용도 인상 깊은데, 두번째 인자 options를 객체화해서 만든 것도 신기하네요!

2023-04-12 07:09 UTC, poco111 commented on src/variables.css
> +:root {
css 변수를 상수화 좋습니다!

2023-04-12 07:13 UTC, poco111 commented on src/components/Header.js
>    setUp() {
class 상속과 오버라이딩 활용이 좋습니다! 저도 공부해볼게요!

2023-04-13 03:13 UTC, crongro requested changes
App.js 만 보면 mounted 가 어떤 역할인지 좀 헷갈립니다. App의 constructor 에서(객체 초기화 단계) 해야할 것 같은 다른 객체 초기화 작업을 mounted 에서 하는것 같기도 해서요.

ViewContainer 디렉토리는 메인뷰에 대한 파일들일까요? 이름만보고 viewConainer 라고 하니 view용 container 모음이라고 생각이 들었네요. 그리고 그 디렉토리 아래에는 view도 있고 view 가 안붙은 파일도 있고 viewcontainer 라는 디렉토리와 동일한 파일도 있고, 조금 정리가 필요합니다. 심지어 어떤 이름은 buttonView가 아니고 viewBtn 이네요.

그러려면 먼저 디렉토리의 역할을 정의하고 그에 맞는 디렉토리 이름을 짓고요.(구조를 표현하기보다는 의미를담은 디렉토리 명)  그 안에 파일도 그 역할에 맞는 이름으로 짓고요. 

addEventlistener의 콜백함수는 분리해서 클래스내에 다른 메서드로 정의해주세요. 특히 복잡한 파일이면 그래야 할 듯.


수고하셨어요. 리뷰 참고해서 전체 구조와 네이밍을 한번 수정해보세요.

2023-04-14 05:47 UTC, crongro approved these changes
수고하셨어요~ 리뷰 좀 남겼어요.

2023-04-14 05:47 UTC, crongro commented on src/components/MainView/MainView.js
> +  mounted() {
mounted  기능이  비교적 복잡하네요.
어떤 일을 하는 지 좀더 잘 드러나게 수정해도 좋을 듯.

2023-04-14 05:47 UTC, crongro commented on src/components/MainView/ListView/ListViewHeader.js
> +        ? categoryIds.reduce((acc, category) => {
이런코드 문법을 많이 쓰긴해요. (템플릿 엔진으로 동작하는 렌더링방식에서)
그래도 reduce 코드가 길면 그 콜백을 분리하는 경우도 있긴하고요.

2023-04-14 05:47 UTC, crongro commented on src/components/MainView/ListView/ListView.js
> +      currentCategoryTotalPage: currentCategoryTotalPage,
key-value 가 같으면 생략할 수 있어요~

new ListViewHeader(listViewHeader, {
  currentPageInCategory,
  currentCategory,
  currentCategoryTotalPage
});

2023-04-14 05:47 UTC, merged