[nanii] 2주차 midpoint
codesquad-members-2023/fe-news pull request #19
Opened 2023-04-10 11:31 UTC by bread1022

2023-04-12 06:39 UTC, ahnlook commented on src/js/components/main/viewContainer/mainView.js
> +  const viewContainer = createEl('div', 'view-container');
class name까지 주는 유틸 만든 거 좋아보여용 :)

2023-04-12 06:44 UTC, ahnlook commented on src/js/core/Store.js
> +  subscribe(fn) {
`fn`은 어떤 줄임말인가용!

2023-04-12 06:47 UTC, ahnlook commented on src/js/stores/dataStore.js
> +    case 'DELIVER_DATA':
case가 하나인데 switch를 쓰신 이유가 있나용! 추가 될 예정인건가요?

2023-04-12 06:50 UTC, ahnlook commented on src/js/stores/viewStore.js
> +      return { ...data };
제가 store 개념을 잘 몰라서, store는 data를 전달하는 역할을 담당하고 있는건가요? 나니 store 파일을 보면 `return { some data }`만 있는 것 같아서 궁금했어요!

2023-04-12 06:51 UTC, ahnlook commented on src/js/utils/fetch.js
> +const fetchData = async (...url) => {
fetch를 어디에 둬야할지 저도 고민 많이 했는데 아예 파일을 빼는 것도 좋아보여용! 이것도 패턴? 디자인의 일부인 건가요?

2023-04-12 06:55 UTC, ahnlook commented on src/js/core/Store.js
> +  constructor(state, reducer) {
`reducer`에는 보통 어떤 것들이 들어오는 건가요?

2023-04-12 07:02 UTC, ahnlook commented on src/js/stores/dataStore.js
> +const dataReducer = (state, actionKey, { responseData }) => {
개인적으로 요즘 객체로 parameter 넘기는 거에 꽂혀서, 이렇게 받아서 처리하는 것도 깔끔할 것 같아용 :)
```
const dataReducer = (dataInformation) => {...}

dataInformation {
    state: // ... ,
    actionKey: // ... ,
    reponseData: // ...
}
```

2023-04-12 07:03 UTC, ahnlook reviewed
코드가 깔끔해서 어려움 없이 이해했어요! 배워갈 부분이 많았습니당 :)

2023-04-13 03:29 UTC, crongro requested changes
상단에서 데이터를 가져오는 등의 비즈니스 작업을 해야 한다면 app 안에서 하는것이 맞긴하고요. 지금처럼 app 함수안에서 다 하지말고 데이터패칭하는 함수를 app.js안에 두고 해도 되긴하죠.

의도를 알수 없는 코드들은 이런거에요.
responseData[0] -> 0이 뭘까.. 'left', 'right' -> 왼쪽, 오른쪽..?뭐지?



datastore 의 data는 무엇인지 알기가 너무 어려워요. 의도를 자세히...

dataReducer 의 switch 문은 case가 하나라서..그냥 조건문으로 해도 되겠어요. 케이스가 더 늘어난다면 switch 가 좋을것 같고요.



components 아래 디렉토리 하나에 하나의 파일로 유지될 거 같으면 디렉토리가 없어도 되긴해요. 그 아래 하위 디렉토리가 있거나 여러파일이 있다면 디렉토리가 필요할 수도 있고요.



core, store, components 라는 역할로 구조를 만든 부분이 좋네요. 

리뷰참고해서 조금 수정해보세요.

2023-04-14 05:59 UTC, crongro approved these changes
수고하셨어요~ 머지해요.

2023-04-14 05:59 UTC, crongro commented on src/js/components/main/viewContainer/grid/grid.js
> +      if(!target.closest('a')) return;
a로 체크하는것도 좋은데 좀더 구체적인 정보를 가지고 판단해도 좋죠.

2023-04-14 05:59 UTC, crongro commented on src/js/components/main/viewContainer/grid/grid.js
> +    gridArea.innerHTML = pressLogoData.map((press) => `<div><img src=${press.mediaInfo.pressLogo}></div>`).join('');
map.join() 은 reduce 로  대체할수있죠.

2023-04-14 05:59 UTC, merged