[워터] w2 학습 계획 및 설계
codesquad-members-2023/fe-news pull request #21
Opened 2023-04-11 08:01 UTC by yesolyo

2023-04-12 06:31 UTC, hoongding commented on script/main.js
>  };
Entry Point가 깔끔하고 좋네요 :)

2023-04-12 06:33 UTC, hoongding commented on script/view/newsHeader.js
> +  return `<span class="date_text">${year}. ${month}. ${date}. ${day}</span>`;
로직이 깔끔하네요!
근데 toLacaleDateString이라는 메서드도 한번 확인해보셔도 좋을거같아요!!

2023-04-12 06:35 UTC, hoongding commented on script/view/rollingBar.js
> +  root.appendChild(newsRollingBar);
컴포넌트에서 직접 root에 넣는 것이 아니라 DOM을 만들어서 Entry Point인 main.js에서 root에 append해보는 방식은 어떨까요?

2023-04-12 06:55 UTC, hoongding commented on script/view/rollingBar.js
> +};
setInterval 대신 RequestAnimationFrame 을 써보는 건 어떨까요?? rAF!! 좋아요!!

2023-04-12 07:09 UTC, hoongding commented on script/controller/controller.js
> +};
코드가 중복이 조금 되는것 같아요! 하나의 함수로 합치는 방법을 생각해봐도 좋을것 같아요!

2023-04-12 07:12 UTC, hoongding commented on script/store/makeData.js
> +  const logoData = document.querySelectorAll(".thumb img");
뭔가 store를 만들때 DOM 조작을 하는 것보다 다른 방법으로 dataSet을 만드는건 어떨까요?

2023-04-12 07:12 UTC, hoongding reviewed
월 화 수고 많으셨어요! 워터! 이번주도 파이팅해보자구용!!🔥

2023-04-13 07:28 UTC, crongro requested changes
답을 드리진 못했고, 고민조금더 해보면서 필요한 부분을 수정해보시죠.



요런 이름도 좋긴합니다.

viewNewsHeader 보다는 NewsHeaderView. 그런데 다시 보니 render링 하는것이니 renderNewsCompanyBar로.

view디렉토리 아래 view들은 렌더링만 하도록 작은 역할로 잘 분리되어 있네요.

새로운 배열 생성할때는 forEach말고 map으로.(makeData.js)

store 에는 변경되는 state가 있고 그 state를 변경할 수 있는 메서드가 있을것 같은데, 그렇지 않고 뭔가 만들기만 하는 형태만 있는것 같아요.

dataset, datalist도 어떤 의미의 배열인지 더 구체적이어야 합니다.

controller가 역할이 늘어날듯 한데 지금 벌써 두 개의 파일로 나눌 필요가 있을까요? 이정도는 합쳐서 처리해도 될 것 같아요.

fetchManager는 유틸리티 같은 이름은데 controller안에 있고 실제로는 데이터 요청과 달리 다른 특정 행동을 하는것이 어색합니다.(어떻게 풀어야할지..음)

선택적으로 수정하시고 다시 커밋/푸시해보세요.

2023-04-14 06:02 UTC, crongro approved these changes
확인 완료~
고민중인거 잘 풀어보세요.

2023-04-14 06:02 UTC, crongro commented on script/main.js
>    fetchManager();
fetchManager 만든것은 좋은데, 뭘 하는지 알수 없는 함수긴해요.
이름은 객체같기도 하고요.

2023-04-14 06:03 UTC, merged