[snoop] W2 midpoint
codesquad-members-2023/fe-news pull request #24
Opened 2023-04-12 06:01 UTC by realsnoopso

# 미리보기

# 학습계획서
https://www.notion.so/snoop-396b5d3634a34f7386dbf999f06dff88?pvs=4

# 한 일
- Observer Pattern, Flux Pattern js코드로 작성하는 방법 공부하기
- user, display store 생성
- store가 변경됨에 따라 Header의 Tab이 변경되도록 작업

# 작업 로그
- 바닐라 자바스크립트로 flux 패턴 만들기 (https://www.notion.so/flux-61670477c3bf43c08e25036336a00171)

# 트러블 슈팅
-

# 고민
- [ ] PressListContents가 너무 비대해지는데 어떻게 해결할지 고민

2023-04-12 06:31 UTC, sarangdaddy commented on prac/observerPattern.js
> +  fire: function (o, thisObj) {
o는 어떤 의미? 의도? 를 가진  파라미터 인가요?

2023-04-12 07:00 UTC, sarangdaddy commented on src/utils/hooks.ts
> +// const [test, setTest, subscribeTest] = useState('메롱');
커밋 전에 주석 지워주세요~ '메롱' (크롱한테 어흥 당해요)

2023-04-13 08:02 UTC, crongro requested changes
utils 쪽에 hooks 은 잘 만들었는데, var 키워드는 왜 사용하세요. 이 코드가 빌드된 코드인가요? for문 사용도 고차함수로 바꾸시고요.

redux 코드에 대해서는 코멘트로 설명좀 해주세요. 설계 당시 고민하셨던 내용을요.

사실 라이브러리는 가독성이 그렇게 중요하지 않은데요. common.ts는 너무 복잡한 코드로 보여요.  리팩토링 하고 진행하면 좋겠어요. return 문 뒤에 코드도 너무 많고요. 매직넘버도 제거하고요.

 store 에 reducer 코드는 매우 좋습니다.

고차함수 구현 중에 들여쓰기기 너무 싶은 코드는 콜백을 분리해서 선언해서 더 많은 함수 사용을 해보세요.(presslistheader.ts 등)

HTMLElement를 상속받는 클래스가 components/controller 에도 있고 /pages/아래에도 있는데요. 어떤것이 뷰지? 라는 생각도 들고 pages 와 컴포넌트는 어떤 차이가 있는것이지? 쉽게 구분이 되지 않습니다.

controller안에 controllerItem파일 이름은 어떤 아이템을 컨트롤 하는지 알기가 어려워요.

전체적으로 계층을 잘 나누고, 유틸이 잘 만들어졌는데, 유틸이 어떻게 쓰이는지 다 확인은 못했네요(redux나 hook 부분)

일단 질문도 남기고 수정할만한 내용도 남겨요.

2023-04-13 08:12 UTC, realsnoopso commented
@crongro 
바닐라 자바스크립트로 flux 패턴 만들기 (https://www.notion.so/flux-61670477c3bf43c08e25036336a00171)
작업 과정은 여기에 올려두었습니다!
redux 라이브러리를 직접 뜯어보고 가져와서 사용해보았는데 redux 코드의 var 가 남아있었던 것을 보신것 같아요! 이건 지금은 업데이트 되었습니다 
이번에는 store에 적용하는 것을 중점적으로 보기 위해 redux 원본 코드를 많이 참고했는데, 한번 새로 코드를 짜보도록 하겠습니다 😅

2023-04-13 08:17 UTC, realsnoopso commented
page와 component는 다시 보니 분류가 애매했던 것 같네요!
모두 view, component가 맞고 component는 common component에 해당합니다.

2023-04-13 08:27 UTC, realsnoopso commented
createCurrentPageIndex 는 안쓰는 함수라 지우도록 하겠습니다! ㅠㅠ

2023-04-14 06:29 UTC, crongro commented
> redux 원본 코드를 많이 참고했는데, 한번 새로 코드를 짜보도록 하겠습니다

좋은 것을 따라서 보고 배우면 학습하는것은 좋은데요.
분명히 내가 설명할 수 있는 코드를 적용하시면 더 좋겠어요.

2023-04-14 06:30 UTC, crongro commented
그리고 리덕스 코드는 좀 어렵고 추천할만한 학습꺼리는 아니라고 봐요. 
더 좋고 인기있고 가벼운 라이브러리가 많아요.
혹시라도 인기있고 잘 만들어졌다고 무조건 그것을 완전한 이해없이 반영하거나 그러지만 않도록 하시고요.

2023-04-14 06:30 UTC, merged